// === ARJ Seed Data (Catálogo base agrícola y clientes) ===
// Proporciona datos de inicio para pruebas, modo demostración o cuando Supabase devuelve 0 filas por RLS.

export const DEFAULT_PRODUCTOS = [
  {
    id: 101,
    cod_alt: 'BOM-JD-5075',
    cod_orig: 'RE505980',
    cod_barras: '759100100101',
    desc: 'Bomba de agua completa con polea John Deere 5075E / 5415 / 5615',
    marca: 'JOHN DEERE',
    marca_modelo: 'JD 5075E / 5415 / 5615',
    sistema: 'Sistema de enfriamiento',
    fob: 48.50,
    stock_vd: 8,
    stock_dist: 16,
    precio_manual: null,
    imagen_url: '',
    origen: 'importado',
    factor_landed: 1.471,
    proveedor: 'A&I Products USA',
    embarque_id: null
  },
  {
    id: 102,
    cod_alt: 'EMB-MF-290',
    cod_orig: '3599462M92',
    cod_barras: '759100100102',
    desc: 'Kit embrague doble 12" (disco cerametálico + prensa) Massey Ferguson 285 / 290',
    marca: 'LUK',
    marca_modelo: 'MF 285 / 290 / 292',
    sistema: 'Embrague',
    fob: 115.00,
    stock_vd: 5,
    stock_dist: 12,
    precio_manual: null,
    imagen_url: '',
    origen: 'importado',
    factor_landed: 1.471,
    proveedor: 'AGCO Parts',
    embarque_id: null
  },
  {
    id: 103,
    cod_alt: 'FIL-DON-P550008',
    cod_orig: 'P550008',
    cod_barras: '742330080010',
    desc: 'Filtro de lubricante motor servicio pesado Donaldson P550008',
    marca: 'DONALDSON',
    marca_modelo: 'UNIVERSAL / FORD / MF',
    sistema: 'Filtros',
    fob: 9.20,
    stock_vd: 35,
    stock_dist: 80,
    precio_manual: null,
    imagen_url: '',
    origen: 'importado',
    factor_landed: 1.471,
    proveedor: 'Donaldson Latam',
    embarque_id: null
  },
  {
    id: 104,
    cod_alt: 'FIL-RAC-R90P',
    cod_orig: 'R90P',
    cod_barras: '759100100104',
    desc: 'Filtro separador agua/combustible Racor Parker 30 micrones serie 900',
    marca: 'PARKER RACOR',
    marca_modelo: 'UNIVERSAL DIESEL',
    sistema: 'Filtros',
    fob: 16.50,
    stock_vd: 20,
    stock_dist: 50,
    precio_manual: null,
    imagen_url: '',
    origen: 'importado',
    factor_landed: 1.471,
    proveedor: 'Parker Hannifin',
    embarque_id: null
  },
  {
    id: 105,
    cod_alt: 'HID-BOSCH-CASE',
    cod_orig: '84254185',
    cod_barras: '759100100105',
    desc: 'Bomba hidráulica tándem engranajes Case IH Maxxum 110 / 125',
    marca: 'BOSCH REXROTH',
    marca_modelo: 'Case IH Maxxum',
    sistema: 'Sistema hidráulico',
    fob: 195.00,
    stock_vd: 3,
    stock_dist: 8,
    precio_manual: null,
    imagen_url: '',
    origen: 'importado',
    factor_landed: 1.471,
    proveedor: 'CNH Industrial',
    embarque_id: null
  },
  {
    id: 106,
    cod_alt: 'DIR-NH-5610',
    cod_orig: '81863398',
    cod_barras: '759100100106',
    desc: 'Terminal de dirección barra axial New Holland TT75 / Ford 5610 / 6610',
    marca: 'ARJ HEAVY',
    marca_modelo: 'New Holland / Ford',
    sistema: 'Tren delantero',
    fob: 24.00,
    stock_vd: 14,
    stock_dist: 30,
    precio_manual: null,
    imagen_url: '',
    origen: 'importado',
    factor_landed: 1.471,
    proveedor: 'ARJ Import',
    embarque_id: null
  },
  {
    id: 107,
    cod_alt: 'MOT-EMP-4236',
    cod_orig: 'U5LT0017',
    cod_barras: '759100100107',
    desc: 'Juego de empacaduras superior con culata motor Perkins 4.236',
    marca: 'PAYEN',
    marca_modelo: 'Perkins 4.236 / MF 285',
    sistema: 'Motor',
    fob: 42.00,
    stock_vd: 7,
    stock_dist: 18,
    precio_manual: null,
    imagen_url: '',
    origen: 'importado',
    factor_landed: 1.471,
    proveedor: 'Federal Mogul',
    embarque_id: null
  },
  {
    id: 108,
    cod_alt: 'RET-CIG-6600',
    cod_orig: '87802875',
    cod_barras: '759100100108',
    desc: 'Estopera cigüeñal trasera teflón con brida Ford 6600 / 6610 / 7610',
    marca: 'CORTECO',
    marca_modelo: 'Ford 6600 / 7610',
    sistema: 'Estoperas',
    fob: 14.50,
    stock_vd: 18,
    stock_dist: 45,
    precio_manual: null,
    imagen_url: '',
    origen: 'importado',
    factor_landed: 1.471,
    proveedor: 'Freudenberg Corteco',
    embarque_id: null
  },
  {
    id: 109,
    cod_alt: 'BUJ-DEL-MF290',
    cod_orig: '180345M1',
    cod_barras: '759100100109',
    desc: 'Buje bocina de eje pivote central y mangueta delantera MF 290',
    marca: 'ARJ HEAVY',
    marca_modelo: 'Massey Ferguson 290',
    sistema: 'Buje-bocina',
    fob: 11.00,
    stock_vd: 22,
    stock_dist: 60,
    precio_manual: null,
    imagen_url: '',
    origen: 'importado',
    factor_landed: 1.471,
    proveedor: 'ARJ Import',
    embarque_id: null
  },
  {
    id: 110,
    cod_alt: 'ELE-ALT-VENIRAN',
    cod_orig: 'AL-1265-VR',
    cod_barras: '759100100110',
    desc: 'Alternador reforzado 12V 65A polea simple Veniran 285 / 399 / 499',
    marca: 'LUCAS DIESEL',
    marca_modelo: 'Veniran 285 / 399',
    sistema: 'Eléctrico',
    fob: 82.00,
    stock_vd: 6,
    stock_dist: 14,
    precio_manual: null,
    imagen_url: '',
    origen: 'importado',
    factor_landed: 1.471,
    proveedor: 'Lucas TVS',
    embarque_id: null
  },
  {
    id: 111,
    cod_alt: 'ELE-ARR-PERKINS',
    cod_orig: '2873K062',
    cod_barras: '759100100111',
    desc: 'Motor de arranque reductor 12V 3.0kW 10 dientes Perkins 1004 / 1006 / 1104',
    marca: 'DELCO REMY',
    marca_modelo: 'Perkins 1004 / MF 390',
    sistema: 'Eléctrico',
    fob: 105.00,
    stock_vd: 4,
    stock_dist: 10,
    precio_manual: null,
    imagen_url: '',
    origen: 'importado',
    factor_landed: 1.471,
    proveedor: 'BorgWarner Remy',
    embarque_id: null
  },
  {
    id: 112,
    cod_alt: 'ENF-TER-JD5000',
    cod_orig: 'RE33705',
    cod_barras: '759100100112',
    desc: 'Termostato de temperatura 82°C con junta sello tórico John Deere serie 5000',
    marca: 'GATES',
    marca_modelo: 'John Deere 5403 / 5075',
    sistema: 'Sistema de enfriamiento',
    fob: 10.50,
    stock_vd: 16,
    stock_dist: 40,
    precio_manual: null,
    imagen_url: '',
    origen: 'importado',
    factor_landed: 1.471,
    proveedor: 'Gates Corp',
    embarque_id: null
  }
];

export const DEFAULT_CLIENTES = [
  {
    id: 201,
    nombre: 'AGROPECUARIA EL TURPIAL C.A.',
    rif: 'J-30492819-1',
    nivel: 'T1',
    tipo: 'credito',
    saldo_vd: 1250.00,
    saldo_dist: 0,
    tel: '0414-5551234',
    empresa: 'ambas',
    origen: 'referido',
    origen_detalle: 'Recomendado por Ing. Morales',
    direccion: 'Carretera Nacional Vía Payara Km 4, Acarigua, Portuguesa',
    notas: 'Cliente VIP desde 2021. Paga puntual cada 15 días.',
    contacto_principal: { nombre: 'Carlos Mendoza', cargo: 'Gerente de Maquinaria', tel: '0414-5551234' },
    contactos_adicionales: [{ nombre: 'Elena Castillo', cargo: 'Administración', tel: '0255-6218844' }]
  },
  {
    id: 202,
    nombre: 'TRACTO REPUESTOS LOS LLANOS S.A.',
    rif: 'J-40192837-0',
    nivel: 'T3',
    tipo: 'credito',
    saldo_vd: 0,
    saldo_dist: 3400.00,
    tel: '0424-5129841',
    empresa: 'distribuidora',
    origen: 'vendedor',
    origen_detalle: 'Ruta Barinas - Guanare',
    direccion: 'Av. 23 de Enero local 14, Barinas',
    notas: 'Distribuidor mayorista en el estado Barinas.',
    contacto_principal: { nombre: 'Ing. José Albarrán', cargo: 'Director de Compras', tel: '0424-5129841' },
    contactos_adicionales: []
  },
  {
    id: 203,
    nombre: 'HACIENDA SAN JOSÉ DE BARINAS',
    rif: 'J-29837482-5',
    nivel: 'T2',
    tipo: 'credito',
    saldo_vd: 450.00,
    saldo_dist: 0,
    tel: '0412-9876543',
    empresa: 'directa',
    origen: 'visita',
    origen_detalle: 'Llegó directo al mostrador',
    direccion: 'Sector Las Delicias, Finca San José, Barinas',
    notas: 'Posee flota de 8 tractores Massey Ferguson y Veniran.',
    contacto_principal: { nombre: 'Roberto Silva', cargo: 'Encargado de Taller', tel: '0412-9876543' },
    contactos_adicionales: []
  },
  {
    id: 204,
    nombre: 'DISTRIBUIDORA AGROVENEZUELA 2020',
    rif: 'J-50123984-2',
    nivel: 'T3',
    tipo: 'contado',
    saldo_vd: 0,
    saldo_dist: 0,
    tel: '0416-3344556',
    empresa: 'ambas',
    origen: 'whatsapp',
    origen_detalle: 'Catálogo digital WhatsApp',
    direccion: 'Zona Industrial Los Próceres, Galpón 9, Turén',
    notas: 'Compras al contado por volumen.',
    contacto_principal: { nombre: 'Mariana Torres', cargo: 'Jefa de Repuestos', tel: '0416-3344556' },
    contactos_adicionales: []
  },
  {
    id: 205,
    nombre: 'PRODUCTORES UNIDOS DE PORTUGUESA',
    rif: 'J-31298471-8',
    nivel: 'T1',
    tipo: 'credito',
    saldo_vd: 890.00,
    saldo_dist: 1200.00,
    tel: '0414-7788990',
    empresa: 'ambas',
    origen: 'feria',
    origen_detalle: 'Expo Portuguesa Productiva',
    direccion: 'Av. Las Lágrimas, Edif. Gremial Piso 2, Araure',
    notas: 'Asociación de cañicultores y maiceros.',
    contacto_principal: { nombre: 'Dr. Fernando Colmenares', cargo: 'Presidente', tel: '0414-7788990' },
    contactos_adicionales: []
  }
];

export const DEFAULT_FACTURAS_COBRAR = [
  {
    id: 'FAC-VD-2026-00142',
    num: 'VD-2026-00142',
    empresa: 'directa',
    cliente: 'AGROPECUARIA EL TURPIAL C.A.',
    cliente_id: 201,
    vendedor: 'JJ',
    fecha: '05 mar 2026',
    fecha_raw: '2026-03-05T14:30:00.000Z',
    vence: '25 mar 2026',
    total: 1250.00,
    abonado: 0.00,
    saldo_pendiente: 1250.00,
    estado: 'pendiente',
    dias: 14,
    tipo_pago: 'credito',
    tasa_par: 58.50,
    tasa_bcv: 47.80,
    descuento_manual: 0,
    pidio_fiscal: true
  },
  {
    id: 'FAC-DT-2026-00088',
    num: 'DT-2026-00088',
    empresa: 'distribuidora',
    cliente: 'TRACTO REPUESTOS LOS LLANOS S.A.',
    cliente_id: 202,
    vendedor: 'HUMBERTO ARJ',
    fecha: '28 feb 2026',
    fecha_raw: '2026-02-28T10:15:00.000Z',
    vence: '20 mar 2026',
    total: 3400.00,
    abonado: 0.00,
    saldo_pendiente: 3400.00,
    estado: 'pendiente',
    dias: 9,
    tipo_pago: 'credito',
    tasa_par: 58.50,
    tasa_bcv: 47.80,
    descuento_manual: 0,
    pidio_fiscal: false
  },
  {
    id: 'FAC-VD-2026-00138',
    num: 'VD-2026-00138',
    empresa: 'directa',
    cliente: 'HACIENDA SAN JOSÉ DE BARINAS',
    cliente_id: 203,
    vendedor: 'JJ',
    fecha: '18 feb 2026',
    fecha_raw: '2026-02-18T16:45:00.000Z',
    vence: '10 mar 2026',
    total: 950.00,
    abonado: 500.00,
    saldo_pendiente: 450.00,
    estado: 'parcial',
    dias: -1,
    tipo_pago: 'credito',
    tasa_par: 58.50,
    tasa_bcv: 47.80,
    descuento_manual: 0,
    pidio_fiscal: false
  }
];

function cargarProductosSemilla() {
  PRODUCTOS.length = 0;
  DEFAULT_PRODUCTOS.forEach(p => PRODUCTOS.push(Object.assign({}, p)));
  console.log('[ARJ] Catálogo semilla cargado: ' + PRODUCTOS.length + ' productos agrícolas.');
}

function cargarClientesSemilla() {
  CLIENTES.length = 0;
  DEFAULT_CLIENTES.forEach(c => CLIENTES.push(JSON.parse(JSON.stringify(c))));
  console.log('[ARJ] Clientes semilla cargados: ' + CLIENTES.length + ' clientes.');
}

function cargarFacturasSemilla() {
  if (FACTURAS_COBRAR.length === 0) {
    DEFAULT_FACTURAS_COBRAR.forEach(f => {
      FACTURAS_COBRAR.push(Object.assign({}, f));
      TODAS_FACTURAS.push(Object.assign({}, f));
      VENTAS_RECIENTES.push({
        id: f.id,
        num: f.num,
        cliente: f.cliente,
        fecha: f.fecha,
        total: f.total,
        vendedor: f.vendedor,
        estado: f.estado
      });
    });
    console.log('[ARJ] Facturas semilla cargadas: ' + FACTURAS_COBRAR.length + ' cuentas por cobrar.');
  }
}
